Semantic page
js-tasks-ru/htmlcss-20240412_danielmt-dm pull request #4
Opened 2024-04-30 12:47 UTC by daniilmatafonov

2024-04-30 12:48 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-05-04 16:04 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-05-04 16:07 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-05-05 13:16 UTC, GSemikozov requested changes

2024-05-05 13:16 UTC, GSemikozov commented on 02-dz0/01-semantic-mockup/page.css
> +:root {
все подобные глобальные стили ни в коем случае не описываем в файлах стилей компонентов. В данном случае переменные должны быть определены в main.css

2024-05-06 09:50 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-05-06 09:52 UTC, daniilmatafonov commented on 02-dz0/01-semantic-mockup/page.css
> +:root {
Спасибо, поправил

2024-05-06 17:50 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-05-08 19:39 UTC, GSemikozov approved these changes

2024-05-08 19:39 UTC, merged